### ISSUE TITLE
Taro编译钉钉小程序命令npm run build:dd -- --watch 报错：TypeError: this.ctx.generateProjectConfig is not a function

### ISSUE THREAD

**Issue by DongDaYo** [NervJS/taro-plugin-platform-alipay-dd#16]
**刚写好的Taro项目，想试着用插件编译成钉钉小程序再进一步开发，于是用了命令npm run build:dd -- --watch，结果报错如下：**
D:\TaroTest\question>npm run dev:dd

> question@1.0.0 dev:dd
> npm run build:dd -- --watch

> question@1.0.0 build:dd
> taro build --type dd "--watch"

👽 Taro v3.4.6

Tips: 预览模式生成的文件较大，设置 NODE_ENV 为 production 可以开启压缩。
Example:
$ set NODE_ENV=production && taro build --type dd --watch

启动  开发者工具-项目目录  D:\TaroTest\question\dist
D:\TaroTest\node_modules\@tarojs\service\dist\platform-plugin-base.js:138
        this.ctx.generateProjectConfig({
                 ^

TypeError: this.ctx.generateProjectConfig is not a function
    at DD.generateProjectConfig (D:\TaroTest\node_modules\@tarojs\service\dist\platform-plugin-base.js:138:18)
    at DD.close (D:\TaroTest\node_modules\@tarojs\plugin-platform-alipay\src\program.ts:38:14)
    at D:\TaroTest\node_modules\@tarojs\service\dist\platform-plugin-base.js:30:115
    at Array.forEach (<anonymous>)
    at Transaction.closeAll (D:\TaroTest\node_modules\@tarojs\service\dist\platform-plugin-base.js:30:18)
    at Transaction.<anonymous> (D:\TaroTest\node_modules\@tarojs\service\dist\platform-plugin-base.js:21:18)
    at Generator.next (<anonymous>)
    at fulfilled (D:\TaroTest\node_modules\@tarojs\service\dist\platform-plugin-base.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**用命令taro build --type dd打包，报的错是一样的：**
D:\TaroTest\question>taro build --type dd
👽 Taro v3.4.6

启动  开发者工具-项目目录  D:\TaroTest\question\dist
D:\TaroTest\node_modules\@tarojs\service\dist\platform-plugin-base.js:138
        this.ctx.generateProjectConfig({
                 ^

TypeError: this.ctx.generateProjectConfig is not a function
    at DD.generateProjectConfig (D:\TaroTest\node_modules\@tarojs\service\dist\platform-plugin-base.js:138:18)
    at DD.close (D:\TaroTest\node_modules\@tarojs\plugin-platform-alipay\src\program.ts:38:14)
    at D:\TaroTest\node_modules\@tarojs\service\dist\platform-plugin-base.js:30:115
    at Array.forEach (<anonymous>)
    at Transaction.closeAll (D:\TaroTest\node_modules\@tarojs\service\dist\platform-plugin-base.js:30:18)
    at Transaction.<anonymous> (D:\TaroTest\node_modules\@tarojs\service\dist\platform-plugin-base.js:21:18)
    at Generator.next (<anonymous>)
    at fulfilled (D:\TaroTest\node_modules\@tarojs\service\dist\platform-plugin-base.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Chen-jj** [comment]
@DongDaYo Taro 版本多少？

**Comment by DongDaYo** [comment]
> 

3.4.6

**Comment by DongDaYo** [comment]
> @DongDaYo Taro 版本多少？

3.4.6

**Comment by Chen-jj** [comment]
先用 3.4.4 试试，可能是已知问题

**Comment by TechQuery** [comment]
飞书小程序在 3.4.6 有一样的 error

**Comment by Chen-jj** [comment]
> 1. 飞书小程序在 `3.4.5`、`3.4.6` 有一样的 error
> 2. 企业微信也一样 [3.4.6版本cli 需要兼容 企业微信插件打包 taro#11644](https://github.com/NervJS/taro/issues/11644)
> 
> 感觉是通用逻辑有 bug

@TechQuery 是的 CLI 有点问题，下周会发版修复~

**Comment by Chen-jj** [comment]
Taro `v3.4.5`、`v3.4.6` CLI 会触发此问题，`v3.4.7` 解决
