### ISSUE TITLE
build提示错误

### ISSUE THREAD

**Issue by wsq547ak** [NervJS/taro-plugin-platform-alipay-dd#4]
我在taro2x版本下使用该插件进行build 钉钉小程序，构建时候报错 提示this.ctx.modifyMiniConfigs is not a function

![image](https://user-images.githubusercontent.com/28085984/104722054-9ef4f100-5768-11eb-99b0-06c2a35d0aa3.png)

有什么办法解决吗

**Comment by wsq547ak** [comment]
(node:50727) UnhandledPromiseRejectionWarning: TypeError: this.ctx.modifyMiniConfigs is not a function
    at DD.modifyMiniConfigs (/Users/user/work/zhs-proj/za-zhonghuishu-mini/node_modules/@tarojs/plugin-platform-alipay/src/program.ts:42:14)
    at DD.start (/Users/user/work/zhs-proj/za-zhonghuishu-mini/node_modules/@tarojs/plugin-platform-alipay/src/program.ts:27:10)
    at Object.fn (/Users/user/work/zhs-proj/za-zhonghuishu-mini/node_modules/@tarojs/plugin-platform-alipay-dd/src/index.ts:10:15)
    at Kernel.<anonymous> (/Users/user/.nvm/versions/node/v13.12.0/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:199:48)
    at Generator.next (<anonymous>)
    at /Users/user/.nvm/versions/node/v13.12.0/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/user/.nvm/versions/node/v13.12.0/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:4:12)
    at /Users/user/.nvm/versions/node/v13.12.0/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:198:33
    at eval (eval at create (/Users/user/.nvm/versions/node/v13.12.0/lib/node_modules/@tarojs/cli/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:14:17)
(node:50727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by Chen-jj** [comment]
只能在taro3.1使用

**Comment by wsq547ak** [comment]
好吧 我试试看升级一下
